kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: jekyll/jekyll
    environment:
      JEKYLL_ENV: production
    commands:
      - chown -R jekyll:jekyll /drone
      - npm install
      - bundle install
      - bundle exec jekyll build
