title: walkah
author: James Walker
description: "James Walker is an independent developer and hacker"
url: https://walkah.net

markdown: kramdown
permalink: blog/:title/
exclude:
  - node_modules/
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json
  - flake.nix
  - flake.lock
  - shell.nix
  - README.md

postcss:
  cache: false

plugins:
  - jekyll-gist
  - jekyll-postcss
